name: Create a new patch release
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/python-release.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/python-release.yml'
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create new patch release
        run: .github/scripts/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}