name: Python Exe
on: 
  push:
    paths:
      - 'src/**'
      - '.github/workflows/python-exe.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/python-exe.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name : Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Create executable
        run: |
          pyinstaller --onefile --noconsole --name "dist/python-exe" ./src/main.py
      - name: Add executable to repository
        run: |
          git add dist/python-exe
          git commit -m "Add executable to repository"
          git push