name: Python Tests
on: 
  push:
    paths:
      - 'src/**'
      - '.github/workflows/python-test.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/python-test.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with unittest
        run: |
          cd src
          python -m unittest unittests.py